# Generated by Django 4.2 on 2023-05-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SneakerCards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
