# Generated by Django 4.2 on 2023-05-01 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SneakerCards', '0002_collector_avatar_alter_cards_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='collector',
        ),
        migrations.AddField(
            model_name='collector',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SneakerCards.deck'),
        ),
        migrations.AddField(
            model_name='deck',
            name='power',
            field=models.IntegerField(null=True),
        ),
    ]
